services:
  app:
    build: .
    container_name: stock-analysis-app
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./.context:/app/.context
      - ./src:/app/src
      - ./data:/app/data
    networks:
      - analytics-network
    depends_on:
      - qdrant
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-db
    ports:
      - "6333:6333" # HTTP & Dashboard
      - "6334:6334" # gRPC
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    networks:
      - analytics-network
    restart: unless-stopped


networks:
  analytics-network:
    driver: bridge